version: "3.8"

services:
  # Angular Frontend Application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: just-add-frontend
    ports:
      - "4200:80"
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development version (uncomment if needed for development)
  # frontend-dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   container_name: just-add-frontend-dev
  #   ports:
  #     - "4200:4200"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   networks:
  #     - app-network
  #   command: npm start

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
